src/BlogBundle/Entity/Category.php
<?php

namespace BlogBundle\Entity;

/**
 * Category
 */
class Category
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $description;

	protected $entry;
	
	public function __construct() {
		$this->entry = new \Doctrine\Common\Collections\ArrayCollection();
	}


	
	/**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Category
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
	
	public function getEntries(){
		return $this->entry;
	}
}

src/BlogBundle/Form/CategoryType.php
<?php

namespace BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class CategoryType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class, array("label"=>"Nombre","required"=>"required", "attr" =>array(
				"class" => "form-name form-control",
			)))
            ->add('description',TextAreaType::class, array("label"=>"Descripcion","required"=>"required", "attr" =>array(
				"class" => "form-name form-control",
			)))
            ->add('Guardar', SubmitType::class, array("attr" =>array(
				"class" => "form-submit btn btn-success",
			)))
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BlogBundle\Entity\Category'
        ));
    }
}

src/BlogBundle/Controller/CategoryController.php
<?php

namespace BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request; 
use Symfony\Component\HttpFoundation\Session\Session; 
use BlogBundle\Entity\Category;
use BlogBundle\Form\CategoryType;

class CategoryController extends Controller
{  private $session;

   public function __construct() {
       $this->session = new Session();
    }
    
    public function indexAction(Request $request){
        $em= $this->getDoctrine()->getManager();
        $categories= $em->getRepository("BlogBundle:Category");
        $categories=$categories->findAll();
        
        return $this->render('BlogBundle:Category:index.html.twig', array(
            "categories"=>$categories,
            ));
        
    }
    

    public function addAction(Request $request){
        $category = new Category();
        $form= $this->CreateForm(CategoryType::class, $category);
        $form->handleRequest($request);
        
        if ($form->isSubmitted()){
            if ($form->isValid()){
                $category= new Category();
                $category->setName($form->get("name")->getData());
                $category->setDescription($form->get("description")->getData());
                $em=$this->getDoctrine()->getManager();
                $em->persist($category);
                $flush=$em->flush();
                if ($flush==null){
                        $status ="Nuevo etiqueta ingresada";
                    }else{
                        $status="no se ah ingresado la etiqueta";
                    }
            }else{
                $status="la etiqueta no se ah creado";
            }
            $this->session->getFlashBag()-> add("status",$status);
            return $this->redirectToRoute("blog_index_category");
        }else{
            $status="la etiqueta no se ah creadooooooooo";  
        }
        
        return $this->render('BlogBundle:Category:add.html.twig', array(
            "form"=>$form->createView(),
            
        ));
    }
     
    public function deleteAction($id){
            $em = $this->getDoctrine()->getEntityManager();
            $category_repo=$em->getRepository("BlogBundle:Category");
            $category=$category_repo->find($id);
            $em->remove($category);
            $em->flush();
            

            return $this->redirectToRoute("blog_index_category");
    }
    
    public function editAction( Request $request,$id){
            $em = $this->getDoctrine()->getEntityManager();
            $category_repo=$em->getRepository("BlogBundle:Category");
            $category=$category_repo->find($id);
            $form= $this->CreateForm(CategoryType::class, $category);
            $form->handleRequest($request);
            if ($form->isSubmitted()){
            if ($form->isValid()){
               
                $category->setName($form->get("name")->getData());
                $category->setDescription($form->get("description")->getData());
                $em=$this->getDoctrine()->getManager();
                $em->persist($category);
                $flush=$em->flush();
                if ($flush==null){
                        $status ="Categoria editada";
                    }else{
                        $status="no se ah podido editars";
                    }
            }else{
                $status="la etiqueta no se ah editado";
            }
            $this->session->getFlashBag()-> add("status",$status);
            return $this->redirectToRoute("blog_index_category");
        }else{
            $status="la etiqueta no se ah creadooooooooo";  
        }
            
            
        return $this->render('BlogBundle:Category:edit.html.twig',array (
            "form"=>$form->createView()
        ));
    }
    
    public function categoryAction ($id){
        $em = $this->getDoctrine()->getEntityManager();
        $category_repo=$em->getRepository("BlogBundle:Category");
        $category=$category_repo->find($id);
        
        return $this->render("BlogBundle:Category:category.html.twig", array(
            "category"=>$category
        ));
    }
}

src/BlogBundle/Resources/views/Category/add.html.twig
{% extends "BlogBundle::layout.html.twig" %}
{% block content %}
    <div class="col-lg-4">
        {{form_start(form, {'action':'', 'method':'POST'})}}
        {{form_end(form)}}
        
    </div>
    <div class="clearfix"></div>

{% endblock %}

src/BlogBundle/Resources/views/Category/category.html.twig
{% extends "BlogBundle::layout.html.twig" %}

{% block menu %}
    {% include "BlogBundle:Category:menuCategories.html.twig" with {"categories": category }  %}
{% endblock %}


{% block content %}


{% for entry in category.entries%}
    <div class="col-lg-11">
        <p class="pull-left" style="margin-right:20px;"><img width="200" src="{{ asset("uploads/"~entry.image)}}"/></p>
        <p><strong>{{entry.title}}</strong></p>
        <p>{{entry.category.name}}</p>
        <p>Autor:{{entry.user.name}}</p>
        
        <p>
            {% for et in entry.entryTag %}
                {{et.tag.name}}
            {% endfor %}
        </p>
        
        <p>
            {%if((app.user.id is defined) and (app.user.id==entry.user.id))%}
                <a href="{{path("blog_entry_edit", {"id":entry.id})}}" class="btn btn-danger">Editar</a>
                <a href="{{path("blog_entry_delete", {"id":entry.id})}}" class="btn btn-danger">Eliminar</a>
            {%endif%}
        </p>

        
       
        <hr/>
    </div>
    
    
{% endfor %}
    

{% endblock %}

src/BlogBundle/Resources/views/Category/edit.html.twig
{% extends "BlogBundle::layout.html.twig" %}
{% block content %}
    <div class="col-lg-4">
        {{form_start(form, {'action':'', 'method':'POST'})}}
        {{form_end(form)}}
        
    </div>
    <div class="clearfix"></div>

{% endblock %}

src/BlogBundle/Resources/views/Category/index.html.twig
{% extends "BlogBundle::layout.html.twig" %}


{% block content %}
    <h2>Todas Las Categorias</h2>
    <div class="col-md-8">
    <hr>
    {%for message in app.session.flashbag().get("status")%}
                <div class="alert alert-success"> {{message}} </div>
    {% endfor %}
    <a href="{{path("blog_category_add")}}" >Añadir Categoria</a>
    <table class="table table-bordered table-striped" >
        <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>
    {%for category in categories%}
           <tr>
            <td>
                {{ category.name }}
             </td>
             <td>
                {{ category.description }}
             </td>
             <td>
                    <a href="{{path("blog_category_edit", {"id":category.id})}}" class="btn btn-info">Editar</a>
               
             </td>
              <td>
                    <a href="{{path("blog_category_delete", {"id":category.id})}}" class="btn btn-danger">Eliminar</a>
               
             </td>

            </tr>
    {%endfor%}
    </table>
    </div>
    <div class="clearfix"></div>
    
{% endblock %}

src/BlogBundle/Resources/views/Category/menuCategories.html.twig
{% for category in categories %}
    <li>
        <a href="{{path("blog_read_category",{"id":category.id})}}">{{category.name}}</a>
       
    </li>
{% endfor %}